export enum LogTypes {
  TYPEORM_CONNECTION = 'TYPEORM CONNECTION',
  SERVER_START = 'SERVER START',
  UNIQUE_VALIDATION_ERROR = 'UNIQUE VALIDATION ERROR',
  DATABASE_ERROR = 'DATABASE ERROR',
  PAYLOAD_VALIDATION_ERROR = 'PAYLOAD VALIDATION ERROR'
}