version: "3.7"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./db-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=todos
    ports:
      - 27017:27017
    networks:
      - webnet
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - 4000:80
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    networks:
      - webnet
    depends_on:
      - db
networks:
  webnet:
volumes:
  pgdata:
